HelloWorld/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

from . import views

urlpatterns = [
    # path('admin/', admin.site.urls),
    (r'runoob', views.runoob),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from .views import index

urlpatterns = [
    path("polls/", include("polls.urls")),
    path('admin/', admin.site.urls),
    path("", index, name="index")
]

mysite/polls/urls.py
from django.urls import path

from . import views

# path()包含四个参数，两个必填参数,route和view.两个可选参数kwargs和name
# route: 匹配URL的准则，当django响应请求时，会从urlpatterns的第一项开始进行匹配。顺序一次知道找到匹配的项。
# route不会匹配get和post参数或者域名。例如在请求127.0.0.1:8000/polls/index和127.0.0.1:8000/polls/index?page=3时，都只会匹配~/polls/index
# view: 当django找到匹配的url后，就会调用view这个特定的视图函数，并传入一个HttpRequest对象作为第一个参数，被捕获的参数以关键字参数的形式传入
app_name = "polls"  # 添加命名空间

# urlpatterns = [
#     # path("index", views.index),
#     path("recall", views.recall, name="recall"),
#     path("", views.index, name="index"),
#     path("<int:question_id>/results/", views.results, name="results"),
#     path("<int:question_id>/vote/", views.vote, name="vote"),
#     path("detail/<int:question_id>/", views.detail, name="detail"),
# ]
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote")
]

mysite/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime

from django.contrib import admin
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.


class Question(models.Model):
    def __str__(self):
        return self.question_text

    # 加上@damin.display装饰器可以使函数在页面中调用
    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?"
    )
    def was_published_recently(self):
        # return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

HelloWorld/views.py
from django.http import HttpResponse
from django.shortcuts import render


def hello(request):
    return HttpResponse("Hello World")


def runoob(request):
    context = {}
    context['hello'] = 'Hello World Heart'
    views_str = "<a href='https://www.runoob.com/'>点击跳转</a>"
    return render(request, 'runoob.html', {"views_str": views_str})

mysite/mysite/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("hello, you're looking my website")

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.urls import reverse
from django.views import generic

from .models import Question, Choice
from django.template import loader
from django.http import Http404
from django.utils import timezone


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        # 返回最近5个发布的question
        # return Question.objects.order_by("-pub_date")[:5]
        """
        return the last five published questions (not including those set to be published in the future)
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


# Create your views here.
# def index(request):
#     return HttpResponse("Hello, world. You're at the polls index.")


def recall(request):
    return HttpResponse("Hello, you're calling this function")


# def blanc(request):
#     return HttpResponse("<h2>hello</h2>")


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})
    # return HttpResponse("You're looking at question %s " % question_id)


def results(request, question_id):
    # response = "You're looking at the result of question %s."
    # return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except(KeyError, Choice.DoesNotExist):
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice."
            }
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # template = loader.get_template("polls/results.html")
        context = {
            "question.id": question.id,
        }
        # 为防止用户点击回退按钮的情况下数据被post两次，所以每次处理完成POST数据后，都需要返回一个HttpResponseRedirect
        return HttpResponse(reverse("polls:results", args=(question.id,)))


def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    output = ", ".join([q.question_text for q in latest_question_list])
    # return HttpResponse(output)
    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))

mysite/views.py
from django.shortcuts import render

# Create your views here.

mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--    <h1>{{ question.question_text }}</h1>-->
<!--    <ul>-->
<!--        {% for choice in question.choice_set.all %}-->
<!--        <li> {{ choice.choice_text}}</li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
    <form action="{% url 'polls:vote' question.id %}" method="post">
<!--       防止csrf攻击生成令牌-->
        {% csrf_token %}
        <fieldset>
            <legend><h1>{{ question.question_text }}</h1></legend>
            {% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
            {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
</body>
</html>

mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_question_list %}
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
    <ul>
        {% for question in latest_question_list %}
<!--            <li><a href="/polls/{{question_id}}">{{ question.question_text }}</a></li>-->
<!--        因为在polls/urls.py中用path()函数通过name参数为URL定义了名字，所以可以使用/{% url %/}代替上面的硬编码-->
<!--            <li><a href="/{% url 'detail'  question.id %/}">{{ question.question_text }}</a></li>-->
<!--        使用命名空间指向具体的应用 'polls:detail'-->
                <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

mysite/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>
    <ul>
        {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} vote {{ choice.votes | pluralize }}
        </li>
        {% endfor %}
    </ul>
    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>

</body>
</html>